-- SOTA ELS USUARIS 'OE_10', 'OE_20' I 'OE_30'
--
-- ATENCIÓ: FALTEN LES PK I FK !!!
--
-- 
CREATE TABLE CATEGORIES_TAB(
	CATEGORY_NAME			VARCHAR2(50), 
	CATEGORY_DESCRIPTION	VARCHAR2(1000),
	CATEGORY_ID				NUMBER(2,0) NOT NULL,
	PARENT_CATEGORY_ID		NUMBER(2,0)
);
ALTER TABLE categories_tab ADD CONSTRAINT cat_PK10 PRIMARY KEY( category_id );
ALTER TABLE categories_tab ADD CONSTRAINT cat_cat_FK10 FOREIGN KEY (parent_category_id) REFERENCES categories_tab(category_id);

--
CREATE TABLE PRODUCT_INFORMATION(
	PRODUCT_ID			NUMBER(6,0) NOT NULL,
	PRODUCT_NAME		VARCHAR2(50),
	PRODUCT_DESCRIPTION	VARCHAR2(2000),
	CATEGORY_ID			NUMBER(2,0),
	WEIGHT_CLASS		NUMBER(1,0),
	WARRANTY_PERIOD		INTERVAL YEAR(2) TO MONTH,
	SUPPLIER_ID			NUMBER(6,0),
	PRODUCT_STATUS		VARCHAR2(20),
	LIST_PRICE			NUMBER(8,2),
	MIN_PRICE			NUMBER(8,2),
	CATALOG_URL			VARCHAR2(50)
);
ALTER TABLE product_information ADD CONSTRAINT pro_PK10 PRIMARY KEY( product_id );
ALTER TABLE product_information ADD CONSTRAINT pro_cat_FK10 FOREIGN KEY (category_id) REFERENCES categories_tab(category_id);


--
CREATE TABLE PRODUCT_DESCRIPTIONS(
	PRODUCT_ID				NUMBER(6,0) NOT NULL,
	LANGUAGE_ID				VARCHAR2(3) NOT NULL,
	TRANSLATED_NAME			NVARCHAR2(50) NOT NULL,
	TRANSLATED_DESCRIPTION	NVARCHAR2(2000) NOT NULL
);
ALTER TABLE product_descriptions ADD CONSTRAINT prd_PK10 PRIMARY KEY( product_id, language_id );
ALTER TABLE product_descriptions ADD CONSTRAINT prd_pro_FK10 FOREIGN KEY (product_id) REFERENCES product_information(product_id);