SET SERVEROUTPUT ON

DECLARE
	i NUMBER := 1; 
BEGIN
    WHILE (i < 10) LOOP
        DBMS_OUTPUT.PUT_LINE( i );
		--
        i := i + 2;
	END LOOP;
END;

DECLARE
	i NUMBER; 
BEGIN
    FOR i IN 1..10 LOOP
		IF ( i IN (1,3,5,7,9) ) THEN
			DBMS_OUTPUT.PUT_LINE( i );
		END IF;
	END LOOP;
END;

DECLARE
	i NUMBER; 
BEGIN
    FOR i IN 1..10 LOOP
        IF (MOD(i,2) = 1) THEN
             DBMS_OUTPUT.PUT_LINE( i );
        END IF;
	END LOOP;
END;