CREATE OR REPLACE TRIGGER trg_order_status_between1	
	BEFORE INSERT OR UPDATE
   	ON ORDERS
    	FOR EACH ROW
BEGIN
   	IF (:NEW.ORDER_MODE = 'direct' AND :NEW.ORDER_STATUS NOT BETWEEN 0 AND 5) THEN
        RAISE_APPLICATION_ERROR(-20003, 'ORDER_STATUS incorrecto debe ser entre 0 y 5');
    ELSIF (:NEW.ORDER_MODE = 'online' AND :NEW.ORDER_STATUS NOT BETWEEN 6 AND 10) THEN
		RAISE_APPLICATION_ERROR(-20003, 'ORDER_STATUS incorrecto debe ser entre 6 y 10');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_order_status_between2
	AFTER INSERT OR UPDATE
	ON ORDERS
	FOR EACH ROW
DECLARE
	dummy VARCHAR2(1);
BEGIN
	SELECT '1' INTO dummy
	FROM EMPLOYEES e
	WHERE e.employee_id    = :NEW.SALES_REP_ID
	AND   e.department_id != 80;
	--
	UPDATE EMPLOYEES
	SET PHONE_NUMBER = NULL
	WHERE EMPLOYEE_ID = :NEW.SALES_REP_ID;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		NULL;
END;

CREATE OR REPLACE TRIGGER trg_order_status
	FOR INSERT OR UPDATE
	ON orders
	COMPOUND TRIGGER

	dummy VARCHAR2(1);

	BEFORE FOR EACH ROW BEGIN
		IF (:NEW.ORDER_MODE = 'direct' AND :NEW.ORDER_STATUS NOT BETWEEN 0 AND 5) THEN
			RAISE_APPLICATION_ERROR(-20003, 'ORDER_STATUS incorrecto debe ser entre 0 y 5');
		ELSIF (:NEW.ORDER_MODE = 'online' AND :NEW.ORDER_STATUS NOT BETWEEN 6 AND 10) THEN
			RAISE_APPLICATION_ERROR(-20003, 'ORDER_STATUS incorrecto debe ser entre 6 y 10');
		END IF;
	END BEFORE FOR EACH ROW;
	
	AFTER EACH ROW BEGIN
		SELECT '1' INTO dummy
		FROM EMPLOYEES e
		WHERE e.employee_id    = :NEW.SALES_REP_ID
		AND   e.department_id != 80;
		--
		UPDATE EMPLOYEES
		SET PHONE_NUMBER = NULL
		WHERE EMPLOYEE_ID = :NEW.SALES_REP_ID;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			NULL;
	END AFTER EACH ROW;
	
END;
