INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '10','Cáceres','11');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '11','Cádiz','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '12','Castellón/Castelló','10');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '13','Ciudad Real','08');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '14','Córdoba','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '15','Coruña, A','12');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '16','Cuenca','08');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '17','Girona','09');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '18','Granada','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '19','Guadalajara','08');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '20','Gipuzkoa','16');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '21','Huelva','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '22','Huesca','02');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '23','Jaén','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '24','León','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '25','Lleida','09');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '26','Rioja, La','17');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '27','Lugo','12');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '28','Madrid','13');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '29','Málaga','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '30','Murcia','14');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '31','Navarra','15');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '32','Ourense','12');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '33','Asturias','03');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '34','Palencia','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '35','Palmas, Las','05');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '36','Pontevedra','12');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '37','Salamanca','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '38','Santa Cruz de Tenerife','05');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '39','Cantabria','06');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '40','Segovia','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '41','Sevilla','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '42','Soria','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '43','Tarragona','09');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '44','Teruel','02');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '45','Toledo','08');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '46','Valencia/València','10');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '47','Valladolid','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '48','Bizkaia','16');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '49','Zamora','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '50','Zaragoza','02');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '51','Ceuta','18');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '52','Melilla','19');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '01','Araba/Álava','16');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '02','Albacete','08');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '03','Alicante/Alacant','10');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '04','Almería','01');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '05','Ávila','07');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '06','Badajoz','11');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '07','Balears, Illes','04');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '08','Barcelona','09');
INSERT INTO provinces(prv_code, prv_name, prv_stt_code) VALUES( '09','Burgos','07');
COMMIT;