INSERT INTO states( stt_code, stt_name ) VALUES( '01','Andalucía');
INSERT INTO states( stt_code, stt_name ) VALUES( '02','Aragón');
INSERT INTO states( stt_code, stt_name ) VALUES( '03','Asturias, Principado de');
INSERT INTO states( stt_code, stt_name ) VALUES( '04','Balears, Illes');
INSERT INTO states( stt_code, stt_name ) VALUES( '05','Canarias');
INSERT INTO states( stt_code, stt_name ) VALUES( '06','Cantabria');
INSERT INTO states( stt_code, stt_name ) VALUES( '07','Castilla y León');
INSERT INTO states( stt_code, stt_name ) VALUES( '08','Castilla - La Mancha');
INSERT INTO states( stt_code, stt_name ) VALUES( '09','Cataluña');
INSERT INTO states( stt_code, stt_name ) VALUES( '10','Comunitat Valenciana');
INSERT INTO states( stt_code, stt_name ) VALUES( '11','Extremadura');
INSERT INTO states( stt_code, stt_name ) VALUES( '12','Galicia');
INSERT INTO states( stt_code, stt_name ) VALUES( '13','Madrid, Comunidad de');
INSERT INTO states( stt_code, stt_name ) VALUES( '14','Murcia, Región de');
INSERT INTO states( stt_code, stt_name ) VALUES( '15','Navarra, Comunidad Foral de');
INSERT INTO states( stt_code, stt_name ) VALUES( '16','País Vasco');
INSERT INTO states( stt_code, stt_name ) VALUES( '17','Rioja, La');
INSERT INTO states( stt_code, stt_name ) VALUES( '18','Ceuta');
INSERT INTO states( stt_code, stt_name ) VALUES( '19','Melilla');
COMMIT;